# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:15-jdk-buster
    resource_class: medium
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}

      - run: gradle dependencies --no-daemon
      - run:
          name: unit
          command: gradle unit --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
  integration:
    docker:
      - image: circleci/openjdk:15-jdk-buster-node
    resource_class: medium
    working_directory: ~/repo

    environment:
      #JAVA_TOOL_OPTIONS: -Xmx3500m
      TERM: dumb
      AWS_REGION: eu-west-1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run: gradle dependencies --no-daemon
      - run:
          name: integration
          command: gradle integration --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
      - run:
          name: upload
          command: gradle upload --no-daemon
      - run: mkdir -p workspace
      - run: echo "export RELEASE_NUMBER=$CIRCLE_BUILD_NUM" > workspace/release_num.txt
      - persist_to_workspace:
          root: workspace
          paths:
           - release_num.txt
  acceptance:
    docker:
      - image: circleci/openjdk:15-jdk-buster-node-browsers
    resource_class: medium
    working_directory: ~/repo

    environment:
      TERM: dumb
      AWS_REGION: eu-west-1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: workspace
      - run:
          name: deployDevForAcceptance
          environment:
            ENV: Dev
          command: |
            source workspace/release_num.txt
            echo release number is $RELEASE_NUMBER
            gradle deploy updateLB tidy --no-daemon
      - run:
          name: setupLocale
          command: |
            sudo sh -c 'echo en_GB.UTF-8 UTF-8 >> /etc/locale.gen'
            sudo locale-gen en_GB.UTF-8
            sudo update-locale LANG=en_GB.UTF-8
      - run:
          name: acceptance
          environment:
            SERVER_URL: https://alpha.tramchester.com
            LANG: "en_GB.UTF-8"
            TZ: "Europe/London"
          command: |
            source workspace/release_num.txt
            echo release number is $RELEASE_NUMBER
            export LANG="en_GB.UTF-8"
            gradle acceptance --no-daemon
      - run:
          name: deployUAT
          environment:
            ENV: UAT
          command: |
            source workspace/release_num.txt
            echo release number is $RELEASE_NUMBER
            gradle deploy updateLB tidy --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
      - store_artifacts:
          path: ~/logs
  deployProd:
    docker:
    # specify the version you desire here
      - image: circleci/openjdk:15-jdk-buster
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
          - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run: gradle dependencies --no-daemon
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
          at: workspace
      - run:
          name: deployProd
          environment:
            ENV: ProdGreen
            AWS_REGION: eu-west-1
          command: |
            source workspace/release_num.txt
            echo release number is $RELEASE_NUMBER
            gradle deploy --no-daemon
            gradle updateLB --no-daemon
workflows:
  version: 2
  build:
    jobs:
    - build
    - integration:
        requires:
          - build
    - acceptance:
        requires:
          - integration
    - hold:
        type: approval
        requires:
          - acceptance
    - deployProd:
        requires:
        - hold