# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    resource_class: medium
    working_directory: ~/repo
    environment:
      RELEASE_NUMBER: << pipeline.number >>
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}

      - run: ./gradlew dependencies --no-daemon
      - run:
          name: unit
          command: ./gradlew unit --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
  integration:
    docker:
      - image: circleci/openjdk:17-jdk-buster-node
    resource_class: medium
    working_directory: ~/repo

    environment:
      #JAVA_TOOL_OPTIONS: -Xmx3500m
      TERM: dumb
      AWS_REGION: eu-west-1
      RELEASE_NUMBER: << pipeline.number >>

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run: ./gradlew dependencies --no-daemon
      - run:
          name: integration
          command: ./gradlew integration --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
      - run:
          name: upload
          command: ./gradlew upload --no-daemon
  acceptance:
    docker:
      - image: circleci/openjdk:17-jdk-buster-node-browsers
    resource_class: medium
    working_directory: ~/repo

    environment:
      TERM: dumb
      AWS_REGION: eu-west-1
      RELEASE_NUMBER: << pipeline.number >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: deployDevForAcceptance
          environment:
            ENV: Dev
          command: |
            echo release number is $RELEASE_NUMBER
            ./gradlew deploy updateLB tidy --no-daemon
      - run:
          name: setupLocale
          command: |
            sudo sh -c 'echo en_GB.UTF-8 UTF-8 >> /etc/locale.gen'
            sudo locale-gen en_GB.UTF-8
            sudo update-locale LANG=en_GB.UTF-8
      - run:
          name: acceptance
          environment:
            # todo move back to proper url
            #SERVER_URL: https://alpha.tramchester.com
            SERVER_URL: http://dev-tramchester-alb-588237683.eu-west-1.elb.amazonaws.com
            LANG: "en_GB.UTF-8"
            TZ: "Europe/London"
          command: |
            echo release number is $RELEASE_NUMBER
            export LANG="en_GB.UTF-8"
            ./gradlew acceptance --no-daemon
#      - run:
#          name: deployUAT
#          environment:
#            ENV: UAT
#          command: |
#            echo release number is $RELEASE_NUMBER
#            ./gradlew deploy updateLB tidy --no-daemon
      - run:
          name: undeployDev
          environment:
            ENV: Dev
          command: |
            echo release number is $RELEASE_NUMBER
            ./gradlew undeploy --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
      - store_artifacts:
          path: ~/logs
  deployProd:
    docker:
    # specify the version you desire here
      - image: circleci/openjdk:17-jdk-buster
    working_directory: ~/repo
    environment:
      RELEASE_NUMBER: << pipeline.number >>
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
          - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run: ./gradlew dependencies --no-daemon
      - run:
          name: deployProd
          environment:
            ENV: ProdGreen
            AWS_REGION: eu-west-1
          command: |
            echo release number is $RELEASE_NUMBER
            ./gradlew deploy --no-daemon
            ./gradlew updateLB --no-daemon
workflows:
  version: 2
  build:
    jobs:
    - build
    - integration:
        requires:
          - build
    - acceptance:
        requires:
          - integration
#    - hold:
#        type: approval
#        requires:
#          - acceptance
#    - deployProd:
#        requires:
#        - hold