# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: medium
    working_directory: ~/repo
    environment:
      RELEASE_NUMBER: << pipeline.number >>
      PLACE : Dev
    steps:
      - checkout
      - run:
          name: compile
          command: ./gradlew --build-cache compileJava
      - run:
          name: compile tests
          command: ./gradlew --build-cache compileTestJava
      - run:
          name: unit
          command: ./gradlew --build-cache unit --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results/unit
      - store_artifacts:
          path: ~/repo/build/reports/tests/unit
      - save_cache:
          name: Gradle deps
          key: v1-gradle-deps-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
  integration:
    docker:
      - image: cimg/openjdk:17.0-node
    resource_class: medium
    working_directory: ~/repo
    environment:
      #JAVA_TOOL_OPTIONS: -Xmx3500m
      TERM: dumb
      AWS_REGION: eu-west-1
      RELEASE_NUMBER: << pipeline.number >>
      ENV: Dev
      PLACE: Dev
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - run:
          name: integration
          command: ./gradlew --build-cache integration --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results/integration
      - store_artifacts:
          path: ~/repo/build/reports/tests/integration
      - run:
          name: upload
          command: ./gradlew --build-cache upload --no-daemon
      - save_cache:
          name: Node deps
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  acceptance:
    docker:
      - image: cimg/openjdk:17.0-browsers
    resource_class: medium
    working_directory: ~/repo

    environment:
      TERM: dumb
      AWS_REGION: eu-west-1
      RELEASE_NUMBER: << pipeline.number >>
      SERVER_URL: "https://alpha.tramchester.com"
      LANG: "en_GB.UTF-8"
      LANGUAGE: "en_GB"
      TZ: "Europe/London"
      ENV: Dev
    steps:
      - browser-tools/install-geckodriver
      # this is broken on circle ci as of 7/May/2024
      #- browser-tools/install-chromedriver
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: report environment
          command:
            echo LANG=$LANG SERVER_URL=$SEVER_URL RELEASE_NUMBER=$RELEASE_NUMBER
      - run:
          name: deployDevForAcceptance
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            ./gradlew --build-cache deploy updateLB tidy --no-daemon
      - run:
          name: setupLocale
          command: |
            sudo sh -c 'echo en_GB.UTF-8 UTF-8 >> /etc/locale.gen'
            sudo locale-gen en_GB.UTF-8
            sudo update-locale LANG=en_GB.UTF-8
      - run:
          name: acceptance
          environment:
          command: |
            echo release number is $RELEASE_NUMBER LANG is $LANG
            ./gradlew --build-cache acceptance --no-daemon
#      - run:
#          name: deployUAT
#          environment:
#            ENV: UAT
#          command: |
#            echo release number is $RELEASE_NUMBER
#            ./gradlew --build-cache deploy updateLB tidy --no-daemon
      - run:
          name: undeployDev
          environment:
            ENV: Dev
          command: |
            echo release number is $RELEASE_NUMBER
            ./gradlew --build-cache undeploy --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results/acceptance
      - store_artifacts:
          path: ~/repo/build/reports/tests/acceptance
      - store_artifacts:
          path: ~/repo/build/reports/tests/screenshots
      - store_artifacts:
          path: ~/logs
  deployProd:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    environment:
      RELEASE_NUMBER: << pipeline.number >>
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-gradle-deps-{{ checksum "build.gradle" }}
      - restore_cache:
          keys:
          - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: deployProd
          environment:
            ENV: ProdBlue
            AWS_REGION: eu-west-1
          command: |
            echo release number is $RELEASE_NUMBER
            ./gradlew --build-cache deploy --no-daemon
            ./gradlew --build-cache updateLB --no-daemon
workflows:
  version: 2
  build:
    jobs:
    - build
    - integration:
        requires:
          - build
    - acceptance:
        requires:
          - integration
    - hold:
        type: approval
        requires:
          - acceptance
    - deployProd:
        requires:
        - hold