server:
  applicationContextPath: /
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: true
    bufferSize: 8KiB
    minimumEntitySize: 160B

secureHost: tramchester.com
staticAssetCacheTimeSeconds: 300
graphDBConfig:
  graphName: buses.db
  neo4jPagecacheMemory: 300m
  initialHeapSize: 100m
  maxHeapSize: 200m
stationClosures: []
gtfsSourceConfig:
  -
    name: tfgm
    dataPath: data/bus
    hasFeedInfo: true
    transportModes: [ bus ]
    transportModesWithPlatforms: []
    noServices: []
remoteSources:
  -
    name: tfgm
    dataURL: ${TRAM_DATAURL:- http://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip}
    dataCheckURL: http://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip
    dataPath: data/bus
    filename: tfgm_data.zip
  -
    name: naptan
    dataURL: https://naptan.app.dft.gov.uk/DataRequest/Naptan.ashx?format=csv
    dataCheckURL: ""
    dataPath: data/naptan
    filename: naptan_csv.zip
  -
    name: postcodes
    dataURL: https://api.os.uk/downloads/v1/products/CodePointOpen/downloads?area=GB&format=CSV&redirect
    dataCheckURL: ""
    dataPath: data/postcodes
    filename: codepo_gb.zip
bounds:
  minEastings: 112685
  minNorthings: 015490
  maxEasting: 619307
  maxNorthings: 1108843
instanceDataUrl: http://169.254.169.254
loadPostcodes: true
createNeighbours: false
distanceToNeighboursKM: 0.4
postcodeDataPath: data/codepo_gb/Data/CSV
postcodeZip: data/codepo_gb.zip
maxWait: 35
maxInitialWait: 45
numberQueries: 3
queryInterval: 20
maxNumberResults: 5
maxWalkingConnections: 3
maxJourneyDuration: 180
nearestStopRangeKM: 1.0
nearestStopForWalkingRangeKM: 0.5
numOfNearestStopsToOffer: 5
numOfNearestStopsForWalking: 50
walkingMPH: 3.0
recentStopsToShow: 5
dataExpiryThreadhold: 3
changeAtInterchangeOnly: true

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO

  appenders:
    - type: console
      threshold: WARN
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: logs/tramchester_buses.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/tramchester_buses-%d.log
      archivedFileCount: 5
      timeZone: UTC
