server:
  type: simple
  applicationContextPath: /
  rootPath: /api/*
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
redirectToSecure: true
secureHost: tramchester.com
staticAssetCacheTimeSeconds: 300
graphDBConfig:
  graphName: databases/tramchesterAcceptance.db
  neo4jPagecacheMemory: 1000m
  memoryTransactionGlobalMaxSize: 650m
distributionBucket: tramchesternewdist
environmentName: ${PLACE}
buildNumber: ${BUILD:- 0}
gtfsSourceConfig:
  -
    name: tfgm
    hasFeedInfo: false
    transportModes: [ tram ]
    transportModesWithPlatforms: [ Tram ]
    initialWaitMinutes: 13
    noServices: []
    markedInterchangesOnly: false
    additionalInterchanges: [9400ZZMAGMX,9400ZZMAPIC]
    groupedStationModes: []
    stationClosures:
      - stations: [ "9400ZZMAEXS" ]
        begin: 2024-02-12
        end: 2024-02-26
        fullyClosed: false
        diversionsOnly: [ 9400ZZMAVIC ]
    addWalksForClosed: true
remoteSources:
  - name: rail
    dataURL: ${RAIL_DATAURL:-s3://tramchesternewdist/railData/ttis928.zip}
    dataCheckURL: ""
    dataPath: data/rail
    downloadPath: data/rail
    filename: rail_data.zip
    defaultExpiryDays: 1
  - name: tfgm
    dataURL: ${TRAM_DATAURL:- https://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip}
    dataCheckURL: https://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip
    dataPath: data/tram
    downloadPath: data/tram
    filename: tfgm_data.zip
    defaultExpiryDays: 1
  - name: naptanxml
    dataURL: ${NAPTAN_DATAURL:- s3://tramchesternewdist/dist/${RELEASE_NUMBER}/NaPTAN.xml.zip}
    dataCheckURL: ""
    dataPath: data/naptan
    downloadPath: data/naptan
    filename: ${NAPTAN_FILE:- NaPTAN.xml.zip}
    defaultExpiryDays: 14
  - name: nptg
    dataURL: ${NPTG_DATAURL:- s3://tramchesternewdist/dist/${RELEASE_NUMBER}/Localities.csv.zip}
    dataCheckURL: ""
    dataPath: data/nptg
    downloadPath: data/nptg
    filename: ${NPTG_FILE:- Localities.csv.zip}
    defaultExpiryDays: 14
  - name: database
    dataURL: s3://tramchesternewdist/dist/${RELEASE_NUMBER}/database.zip
    dataCheckURL: s3://tramchesternewdist/dist/${RELEASE_NUMBER}/database.zip
    dataPath: databases
    downloadPath: databases
    filename: database.zip
    defaultExpiryDays: 0
    modTimeCheckFilename: gm_rail.db
    mandatory: false
    skipUpload: false
rail:
  dataPath: data/rail
  version: 928
  modes: [ Train, RailReplacementBus ]
  initialWaitMinutes: 60
cacheFolder: data/cache
calcTimeoutMillis: 3500
bounds:
  minEastings: 370000
  minNorthings: 380000
  maxEasting: 398500
  maxNorthings: 414500
tfgmTramliveData:
  dataUrl: ${LIVEDATA_URL:- "sns://tramchester_live_data_ProdBlue"}
  dataSubscriptionKey: ${TFGMAPIKEY:- ""}
  s3Bucket: ""
  s3Prefix: ${PLACE:- "test"}
  refreshPeriodSeconds: 20
  maxNumberStationsWithoutMessages: 10
  maxNumberStationsWithoutData: 5
instanceDataUrl: http://169.254.169.254
planningEnabled: true
neighbourConfig:
  maxNeighbourConnections: 3
  distanceToNeighboursKM: 0.2
  additional:
    - first: "9400ZZMAEDY"
      second: "EDIDBRY"
    - first: "9400ZZMAECC"
      second: "ECCLES"
    - first: "9400ZZMAAUL"
      second: "ASHONUL"
maxWait: 25
maxNumberResults: 5
maxJourneyDuration:  127
numberQueries: 3
queryInterval: 10
depthFirst: true
maxWalkingConnections: 3
nearestStopRangeKM: 1.6
nearestStopForWalkingRangeKM: 1.6
numOfNearestStopsToOffer:  5
numOfNearestStopsForWalking:  3
walkingMPH: 3
recentStopsToShow: 5
dataExpiryThreadhold: 3
changeAtInterchangeOnly: true
sendCloudWatchMetrics: false
cloudWatchMetricsFrequencyMinutes: 2

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO
  loggers:
    root: INFO
    com.tramchester: INFO
    org.eclipse.jetty.servlet: INFO
    io.dropwizard.jersey.jackson: INFO

  appenders:
    - type: console
      threshold: WARN
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: build/reports/tests/accept_tramchester.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: build/reports/tests/accept_tramchester-%d.log
      archivedFileCount: 5
      timeZone: UTC
