server:
  applicationContextPath: /
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: true
    bufferSize: 8KiB
    minimumEntitySize: 160B

secureHost: tramchester.com
staticAssetCacheTimeSeconds: 300
graphDBConfig:
  graphName: trains.db
  neo4jPagecacheMemory: 1000m
  initialHeapSize: 100m
  maxHeapSize: 200m
gtfsSourceConfig:
  -
    name: gbRail
    dataPath: data/trains
    hasFeedInfo: false
    transportModes: [ train, bus, subway, ferry, replacementBus ]
    transportModesWithPlatforms: []
    noServices: []
    additionalInterchanges: []
    compositeStationModes: []
remoteSources:
  -
    name: gbRail
    dataURL: https://s3.eu-west-2.amazonaws.com/feeds.planar.network/gb-rail-latest.zip
    dataCheckURL: https://s3.eu-west-2.amazonaws.com/feeds.planar.network/gb-rail-latest.zip
    dataPath: data/trains
    filename: gb-rail-latest.zip
  -
    name: naptan
    dataURL: https://naptan.app.dft.gov.uk/DataRequest/Naptan.ashx?format=csv
    dataCheckURL: ""
    dataPath: data/naptan
    filename: naptan_csv.zip
cacheFolder: data/cacheTrains
bounds:
  minEastings: 147588
  minNorthings: 30599
  maxEasting: 654747
  maxNorthings: 967921
stationClosures: []
instanceDataUrl: http://169.254.169.254
createNeighbours: false
distanceToNeighboursKM: 0.4
maxWait: 35
maxInitialWait: 25
numberQueries: 6
queryInterval: 20
maxWalkingConnections: 3
maxNumberResults: 5
maxJourneyDuration: 840
nearestStopRangeKM: 1.6
nearestStopForWalkingRangeKM: 1.6
numOfNearestStopsToOffer: 5
numOfNearestStopsForWalking: 3
walkingMPH: 3.0
recentStopsToShow: 5
dataExpiryThreadhold: 3
changeAtInterchangeOnly: true
sendCloudWatchMetrics: true

swagger:
  resourcePackage: com.tramchester.resources
  title: tramchester

logging:
  level: INFO

  appenders:
    - type: console
      threshold: INFO
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: logs/tramchester_trains.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/tramchester_trains-%d.log
      archivedFileCount: 5
      timeZone: UTC
