gtfsSourceConfig:
  - name: tfgm
    hasFeedInfo: false
    transportModes: [ tram ]
    transportModesWithPlatforms: [ Tram ]
    initialWaitMinutes: 13
    noServices: []
    markedInterchangesOnly: false
    additionalInterchanges: [ 9400ZZMAMCU, 9400ZZMAPIC, 9400ZZMAECS]
    groupedStationModes: []
    addWalksForClosed: true
    stationClosures:
      - stations:
          ids: [ 9400ZZMASHU, 9400ZZMAMKT ]
        dateRange:
          begin: 2026-09-21
          end: 2026-09-26
        fullyClosed: true
        diversionsAroundClosure: [ ]
        diversionsToFromClosure: [ ]
      - stations:
          ids: [ "9400ZZMAPGD" ]
        dateRange:
          begin: 2026-09-27
          end: 2026-10-03
        fullyClosed: true
        diversionsAroundClosure: [ 9400ZZMASTP, 9400ZZMAPIC, 9400ZZMAMKT ]
        diversionsToFromClosure: [ ]
    temporaryStationsWalks:
    - stations:
        first: 9400ZZMAMCU
        second: 9400ZZMAIWM
      begin: 2026-09-01
      end: 2026-10-15
remoteSources:
  - name: tfgm
    dataURL: ${TRAM_DATAURL:- s3://tramchesternewdist/dist/${RELEASE_NUMBER}/tfgm_data.zip}
    dataCheckURL: https://odata.tfgm.com/opendata/downloads/TfGMgtfsnew.zip
    dataPath: data/tram
    downloadPath: data/tram
    filename: tfgm_data.zip
    defaultExpiryDays: 1
  - name: database
#    skip:
#      config: inMemoryGraph
    dataURL: ${DB_DATAURL:- s3://tramchesternewdist/dist/${RELEASE_NUMBER}/database.zip}
    dataCheckURL: ${DB_DATAURL:- s3://tramchesternewdist/dist/${RELEASE_NUMBER}/database.zip}
    dataPath: databases
    downloadPath: databases
    filename: database.zip
    defaultExpiryDays: 0
    modTimeCheckFilename: tramchester
    mandatory: false
    skipUpload: false
bounds:
  minEastings: 333200
  minNorthings: 373130
  maxEasting: 414500
  maxNorthings: 437850